# Generated by Django 4.2.27 on 2025-12-12 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
